# Generated by Django 3.0.1 on 2020-01-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_forum', '0002_auto_20200101_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
